/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package request.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author balar
 */
public class Registation extends javax.swing.JFrame {
    int pin;
    long empid;
    String type,email,name,fname,dob,gender,marital,username,password,address,city,state;
    
    

    /**
     * Creates new form Registation
     */
    public Registation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        b4 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        b2 = new javax.swing.JRadioButton();
        t7 = new javax.swing.JPasswordField();
        t10 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(132, 175, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel1.setText("Type");

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registration Form");

        c1.setBackground(new java.awt.Color(153, 204, 255));
        c1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "EMPLOYEE", "MANAGER" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel4.setText("Marital Status");

        t2.setBackground(new java.awt.Color(204, 204, 204));
        t2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel5.setText("Father Name");

        t3.setBackground(new java.awt.Color(204, 204, 204));
        t3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel6.setText("Date of birth");

        t4.setBackground(new java.awt.Color(204, 204, 204));
        t4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel7.setText("Gender");

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        b1.setText("Male");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel8.setText("Username");

        t6.setBackground(new java.awt.Color(204, 204, 204));
        t6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel9.setText("Address");

        t8.setBackground(new java.awt.Color(204, 204, 204));
        t8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel10.setText("Password");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel11.setText("Email Id");

        t5.setBackground(new java.awt.Color(204, 204, 204));
        t5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(b4);
        b4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        b4.setText("Unmarried");

        buttonGroup2.add(b3);
        b3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        b3.setText("Married");

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel12.setText("City");

        t9.setBackground(new java.awt.Color(204, 204, 204));
        t9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel13.setText("Pin Code");

        t11.setBackground(new java.awt.Color(204, 204, 204));
        t11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel14.setText("State");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(b2);
        b2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        b2.setText("Female");

        t7.setBackground(new java.awt.Color(204, 204, 204));
        t7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        t10.setBackground(new java.awt.Color(204, 204, 204));
        t10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andhra Pradesh", "Assam", "Bihar", "Jharkhand", "Kerala", "Madhya Pradesh", "Odisha", "Punjab", "Rajasthan", "Tamil Nadu", "Uttar Pradesh", "West Bengal" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(t11, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(b4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t7)
                    .addComponent(t10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3)
                    .addComponent(b4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(t10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                                  
    
        // Initialize variables from form fields
        if (t2.getText().isEmpty() || t3.getText().isEmpty() || t4.getText().isEmpty() ||
            t5.getText().isEmpty() || t6.getText().isEmpty() || t7.getText().isEmpty() || t8.getText().isEmpty() ||
            t9.getText().isEmpty() || t10.getSelectedItem().toString().isEmpty() || t11.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "All fields are required.");
          
        }else{
          try{
        // Initialize variables from form fields
        Random ran=new Random();
       // random=Math.abs((ran.nextLong() % 9000L) + 1000L);
        
        empid =Math.abs((ran.nextLong() % 9000L) + 1000L); 
        name = t2.getText();
        fname = t3.getText();
        dob = t4.getText();
        email = t5.getText();
        username = t6.getText();
        password = t7.getText();
        address = t8.getText();
        city = t9.getText();
        state = t10.getSelectedItem().toString();
        pin = Integer.parseInt(t11.getText());
        type = c1.getSelectedItem().toString();
        gender = b1.isSelected() ? "Male" : "Female";
        marital = b3.isSelected() ? "Married" : "Unmarried";
       
        if (!name.matches("^[a-zA-Z\\s'-]+$")) {
    JOptionPane.showMessageDialog(null, "Invalid Name.");
} else if (!fname.matches("^[a-zA-Z\\s'-]+$")) {
    JOptionPane.showMessageDialog(null, "Invalid Father Name.");
} else {
        
       
   if (password.length() > 10) {
    JOptionPane.showMessageDialog(null, "Password should not be greater than 10 characters.");
} else if (!password.matches(".*[!@#$%^&*(),.?\":{}|<>].*")) {
    JOptionPane.showMessageDialog(null, "Password must contain at least one special character.");
} else{
       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
sdf.setLenient(false); // Strict date validation
try {
    Date dobDate = sdf.parse(dob);

    // Get current date
    Date currentDate = new Date();

    // Create a calendar to represent the date 100 years ago
    Calendar cal = Calendar.getInstance();
    cal.setTime(currentDate);
    cal.add(Calendar.YEAR, -100);
    Date hundredYearsAgo = cal.getTime();

    // Check if DOB is in the future or more than 100 years in the past
    if (dobDate.after(currentDate)) {
        JOptionPane.showMessageDialog(null, "Date of Birth cannot be in the future.");
        return;
    } else if (dobDate.before(hundredYearsAgo)) {
        JOptionPane.showMessageDialog(null, "Date of Birth cannot be more than 100 years ago.");
        return;
    }
} catch (ParseException e) {
    JOptionPane.showMessageDialog(null, "Invalid Date of Birth. Please use the format dd/MM/yyyy.");
    return;
}
 
     /* SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
      sdf.setLenient(false); // Strict date validation
      try {
      Date dobDate = sdf.parse(dob);

    // Check if DOB is a future date
    if (dobDate.after(new Date())) {
        JOptionPane.showMessageDialog(null, "Date of Birth cannot be in the future.");
        return;
    }
   }catch (ParseException e) {
    JOptionPane.showMessageDialog(null, "Invalid Date of Birth. Please use the format dd/MM/yyyy.");
    return;
}*/
      
     
   if (!email.matches("^[\\w-\\.]+@gmail\\.com")) {
            JOptionPane.showMessageDialog(null, "Invalid Email");
            return;
        }
    if(t11.getText().length()!=6){
       JOptionPane.showMessageDialog(null, "Invalid Pin ");
            return;   
      }

   
       
       if(type.equals("ADMIN")){
        
     try {
   // int id = Integer.parseInt(t1.getText());
double id=empid;
    // Load the Oracle JDBC driver
    Class.forName("oracle.jdbc.driver.OracleDriver");

    // Establish the connection
    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Rudra@7978");

    // Query to check if the employee ID already exists
    String query = "SELECT empid FROM ADMIN WHERE empid = ?";
    PreparedStatement ps = con.prepareStatement(query);
    ps.setDouble(1, id);

    // Execute the query
    ResultSet rs = ps.executeQuery();

    // Check if the employee ID exists
    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "You have already registered Please Log in .");
    } else {
        // If employee ID does not exist, proceed with insertion
        String insertQuery = "INSERT INTO ADMIN (type, empid, name, father, dob, gender, email, marital, username, password, address, city, state, pin) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement insertPs = con.prepareStatement(insertQuery);

        // Set parameters
        insertPs.setString(1, type);
        insertPs.setDouble(2, empid);
        insertPs.setString(3, name);
        insertPs.setString(4, fname);
        insertPs.setString(5, dob);
        insertPs.setString(6, gender);
        insertPs.setString(7, email);
        insertPs.setString(8, marital);
        insertPs.setString(9, username);
        insertPs.setString(10, password);
        insertPs.setString(11, address);
        insertPs.setString(12, city);
        insertPs.setString(13, state);
        insertPs.setInt(14, pin);

        // Execute the insertion
        insertPs.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registration Successful\n Your Employee ID is "+empid);
       /* t1.setText("");t2.setText("");t3.setText("");t4.setText("");t5.setText("");t6.setText("");
        t7.setText(""); t8.setText(""); t9.setText(""); t10.setText(""); t11.setText("");
        b1.setSelected(false);  b2.setSelected(false);  b3.setSelected(false);  b4.setSelected(false); */
        
        
        // Close the PreparedStatement for insertion
        insertPs.close();
    }

    // Close the ResultSet, PreparedStatement, and Connection
    rs.close();
    ps.close();
    con.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
     
}

       
        if(type.equals("EMPLOYEE")){
        
        try {
    //int id = Integer.parseInt(t1.getText());
     double id=empid;
    // Load the Oracle JDBC driver
    Class.forName("oracle.jdbc.driver.OracleDriver");

    // Establish the connection
    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Rudra@7978");

    // Query to check if the employee ID already exists
    String query = "SELECT empid FROM EMPLOYEE WHERE empid = ?";
    PreparedStatement ps = con.prepareStatement(query);
    ps.setDouble(1, id);

    // Execute the query
    ResultSet rs = ps.executeQuery();

    // Check if the employee ID exists
    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "You have already registered Please Log in .");
    } else {
        // If employee ID does not exist, proceed with insertion
        String insertQuery = "INSERT INTO EMPLOYEE (type, empid, name, father, dob, gender, email, marital, username, password, address, city, state, pin) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement insertPs = con.prepareStatement(insertQuery);

        // Set parameters
        insertPs.setString(1, type);
        insertPs.setDouble(2, empid);
        insertPs.setString(3, name);
        insertPs.setString(4, fname);
        insertPs.setString(5, dob);
        insertPs.setString(6, gender);
        insertPs.setString(7, email);
        insertPs.setString(8, marital);
        insertPs.setString(9, username);
        insertPs.setString(10, password);
        insertPs.setString(11, address);
        insertPs.setString(12, city);
        insertPs.setString(13, state);
        insertPs.setInt(14, pin);

        // Execute the insertion
        insertPs.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registration Successful\n Your Employee ID is "+empid);
       /* t1.setText("");t2.setText("");t3.setText("");t4.setText("");t5.setText("");t6.setText("");
        t7.setText(""); t8.setText(""); t9.setText(""); t10.setText(""); t11.setText("");
        b1.setSelected(false);  b2.setSelected(false);  b3.setSelected(false);  b4.setSelected(false); */
        
        // Close the PreparedStatement for insertion
        insertPs.close();
    }

    // Close the ResultSet, PreparedStatement, and Connection
    rs.close();
    ps.close();
    con.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
     
 }
    if(type.equals("MANAGER")){

        try {
    double id = empid;

    // Load the Oracle JDBC driver
    Class.forName("oracle.jdbc.driver.OracleDriver");

    // Establish the connection
    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Rudra@7978");

    // Query to check if the employee ID already exists
    String query = "SELECT empid FROM MANAGER WHERE empid = ?";
    PreparedStatement ps = con.prepareStatement(query);
    ps.setDouble(1, id);

    // Execute the query
    ResultSet rs = ps.executeQuery();

    // Check if the employee ID exists
    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "You have already registered Please Log in .");
    } else {
        // If employee ID does not exist, proceed with insertion
        String insertQuery = "INSERT INTO MANAGER (type, empid, name, father, dob, gender, email, marital, username, password, address, city, state, pin) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement insertPs = con.prepareStatement(insertQuery);

        // Set parameters
        insertPs.setString(1, type);
        insertPs.setDouble(2, empid);
        insertPs.setString(3, name);
        insertPs.setString(4, fname);
        insertPs.setString(5, dob);
        insertPs.setString(6, gender);
        insertPs.setString(7, email);
        insertPs.setString(8, marital);
        insertPs.setString(9, username);
        insertPs.setString(10, password);
        insertPs.setString(11, address);
        insertPs.setString(12, city);
        insertPs.setString(13, state);
        insertPs.setInt(14, pin);

        // Execute the insertion
        insertPs.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registration Successful\n Your Employee ID is "+empid);
     /*  t1.setText("");t2.setText("");t3.setText("");t4.setText("");t5.setText("");t6.setText("");
        t7.setText(""); t8.setText(""); t9.setText(""); t10.setText(""); t11.setText("");
          b1.setSelected(false); b2.setSelected(false); b3.setSelected(false); b4.setSelected(false);*/
        // Close the PreparedStatement for insertion
        insertPs.close();
    }

    // Close the ResultSet, PreparedStatement, and Connection
    rs.close();
    ps.close();
    con.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
 }   
}
}
  } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numeric values for Employee ID and PIN.");
    } 

}
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JPasswordField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
